services:
  - type: web
    name: rewrite-academy
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn classdoodle.web_app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
