services:
  - type: web
    name: rewrite-academy
    runtime: python
    pythonVersion: 3.11.0
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
